name: 'Setup Ubuntu20.04'
description: 'Install all the needed standard packages using apt and pip.'

runs:
  using: "composite"
  steps:
    #
    # build and install all dependencies.
    #

    # apt dependencies.
    - name: "apt install"
      shell: bash 
      run: |
        sudo apt update && \
          sudo apt install -y build-essential \
          python3-pip \
          cmake \
          libcereal-dev \
          libyaml-cpp-dev \
          libboost-all-dev \
          libgtest-dev \
          libeigen3-dev \
          libedit-dev \
          doxygen \
          libncurses5-dev \
          freeglut3-dev \
          libxmu-dev \
          git \
          ssh \
          lsb-release

    # pip dependencies.
    - name: "pip install"
      shell: bash
      run: |
        sudo -H pip3 install -U pip
        sudo -H pip3 install "setuptools>=40.0" && \
        sudo -H pip3 install -U \
          colcon-common-extensions \
          treep \
          fyplot \
          pyside2 \
          empy \
          flake8 \
          m2r \
          mistune<2.0.0 \
          sphinx \
          pyjson \
          recommonmark \
          sphinx_rtd_theme \
          sphinxcontrib-moderncmakedomain \
          breathe \
          pytest \
          gcovr

    # Setup git account:
    - name: Set git account
      shell: bash
      run: |
        git config --global user.email "mnaveau@tue.mpg.de"
        git config --global user.name "MPI-IS-BambooAgent"
