name: 'Setup laas packages'
description: 'Install all the needed standard laas packages.'

runs:
  using: "composite"
  steps:
      # Add the robotpkg ppa. This contains the LAAS laboratory code base.
      # Typically: pinocchio, dynamic-graph, gepetto-viewer, sot-core, ...
      - name: "add the robotpkg ppa"
        shell: bash
        run: |
          sudo sh -c 'echo "deb [arch=amd64] http://robotpkg.openrobots.org/wip/packages/debian/pub $(lsb_release -sc) robotpkg" > /etc/apt/sources.list.d/robotpkg-openrobots.list'
          sudo sh -c 'echo "deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -sc) robotpkg" >> /etc/apt/sources.list.d/robotpkg-openrobots.list'
          curl http://robotpkg.openrobots.org/packages/deb
          
      # LAAS dependencies.
      - name: "Update"
        shell: bash 
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ADD535E05E56C3FD
          sudo apt-get update --fix-missing
          sudo apt-get -y install -f
          sudo apt-get -y upgrade
        
      - name: "apt install LAAS packages"
        shell: bash 
        run: |
          if [[ `lsb_release -d` == *"20.04"* ]]; then
            sudo apt-get install -y \
              robotpkg-py38-qt5-gepetto-viewer-corba \
              robotpkg-py38-tsid \
              robotpkg-py38-dynamic-graph-v3 \
              robotpkg-py38-eigenpy \
              robotpkg-py38-pinocchio \
              robotpkg-py38-parametric-curves \
              robotpkg-py38-sot-core-v3 \
              robotpkg-py38-quadprog \
              robotpkg-py38-sot-dynamic-pinocchio-v3
          elif [[ `lsb_release -d` == *"18.04"* ]]; then
            sudo apt-get install -y \
              robotpkg-py36-qt5-gepetto-viewer-corba \
              robotpkg-py36-tsid \
              robotpkg-py36-dynamic-graph-v3 \
              robotpkg-py36-eigenpy \
              robotpkg-py36-pinocchio \
              robotpkg-py36-parametric-curves \
              robotpkg-py36-sot-core-v3 \
              robotpkg-py36-quadprog \
              robotpkg-py36-sot-dynamic-pinocchio-v3
          fi
          
      
      - name: "Install the setup.bash for that detup the environment variables"
        shell: bash
        run: |
          sudo sh -c 'echo "#! /bin/bash" > /opt/openrobots/setup.bash'
          sudo sh -c 'echo "" >> /opt/openrobots/setup.bash'
          sudo sh -c 'echo "export PATH=\"/opt/openrobots/bin:\$PATH\"" >> /opt/openrobots/setup.bash'
          sudo sh -c 'echo "export PKG_CONFIG_PATH=\"/opt/openrobots/lib/pkgconfig:\$PKG_CONFIG_PATH\"" >> /opt/openrobots/setup.bash'
          sudo sh -c 'echo "export LD_LIBRARY_PATH=\"/opt/openrobots/lib:\$LD_LIBRARY_PATH\"" >> /opt/openrobots/setup.bash'
          sudo sh -c 'echo "export LD_LIBRARY_PATH=\"/opt/openrobots/lib/dynamic-graph-plugins:\$LD_LIBRARY_PATH\"" >> /opt/openrobots/setup.bash'
          if [[ `lsb_release -d` == *"20.04"* ]]; then
            sudo sh -c 'echo "export PYTHONPATH=\"/opt/openrobots/lib/python3.8/site-packages:\$PYTHONPATH\"" >> /opt/openrobots/setup.bash'
          elif [[ `lsb_release -d` == *"18.04"* ]]; then
            sudo sh -c 'echo "export PYTHONPATH=\"/opt/openrobots/lib/python3.6/site-packages:\$PYTHONPATH\"" >> /opt/openrobots/setup.bash'
          fi
          sudo sh -c 'echo "export ROS_PACKAGE_PATH=\"/opt/openrobots/share:\$ROS_PACKAGE_PATH\"" >> /opt/openrobots/setup.bash'
          sudo sh -c 'echo "export CMAKE_PREFIX_PATH=\"/opt/openrobots:\$CMAKE_PREFIX_PATH\"" >> /opt/openrobots/setup.bash'
          sudo chown -R root:root /opt/openrobots
